name: Dev

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  BUILD_TYPE: core
  DEFAULT_PYTHON: 3.8

jobs:
  any_name:
    runs-on: ubuntu-latest
    steps:
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo "$SECRET_NAME" > data.txt
          cat data.txt
        env:
          SECRET_NAME: ${{ secrets.SECRET_NAME }}
      - uses: actions/upload-artifact@v4
        with:
          name: data
          path: data.txt
